// Code generated by protoc-gen-go. DO NOT EDIT.
// source: triton.proto

package triton

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hint int32

const (
	// Unspecified. This value must not be used.
	Hint_HINT_UNSPECIFIED      Hint = 0
	Hint_DO_NOT_CACHE          Hint = 1
	Hint_IGNORE_CACHE          Hint = 2
	Hint_ALWAYS_USE_BULK_STORE Hint = 3
	Hint_DO_NOT_USE_BULK_STORE Hint = 4
)

var Hint_name = map[int32]string{
	0: "HINT_UNSPECIFIED",
	1: "DO_NOT_CACHE",
	2: "IGNORE_CACHE",
	3: "ALWAYS_USE_BULK_STORE",
	4: "DO_NOT_USE_BULK_STORE",
}

var Hint_value = map[string]int32{
	"HINT_UNSPECIFIED":      0,
	"DO_NOT_CACHE":          1,
	"IGNORE_CACHE":          2,
	"ALWAYS_USE_BULK_STORE": 3,
	"DO_NOT_USE_BULK_STORE": 4,
}

func (x Hint) String() string {
	return proto.EnumName(Hint_name, int32(x))
}

func (Hint) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{0}
}

type StructuredData struct {
	// Types that are valid to be assigned to Value:
	//	*StructuredData_IntegerValue
	//	*StructuredData_StringValue
	//	*StructuredData_BooleanValue
	Value                isStructuredData_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StructuredData) Reset()         { *m = StructuredData{} }
func (m *StructuredData) String() string { return proto.CompactTextString(m) }
func (*StructuredData) ProtoMessage()    {}
func (*StructuredData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{0}
}

func (m *StructuredData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructuredData.Unmarshal(m, b)
}
func (m *StructuredData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructuredData.Marshal(b, m, deterministic)
}
func (m *StructuredData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructuredData.Merge(m, src)
}
func (m *StructuredData) XXX_Size() int {
	return xxx_messageInfo_StructuredData.Size(m)
}
func (m *StructuredData) XXX_DiscardUnknown() {
	xxx_messageInfo_StructuredData.DiscardUnknown(m)
}

var xxx_messageInfo_StructuredData proto.InternalMessageInfo

type isStructuredData_Value interface {
	isStructuredData_Value()
}

type StructuredData_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,1,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type StructuredData_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type StructuredData_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,3,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

func (*StructuredData_IntegerValue) isStructuredData_Value() {}

func (*StructuredData_StringValue) isStructuredData_Value() {}

func (*StructuredData_BooleanValue) isStructuredData_Value() {}

func (m *StructuredData) GetValue() isStructuredData_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *StructuredData) GetIntegerValue() int64 {
	if x, ok := m.GetValue().(*StructuredData_IntegerValue); ok {
		return x.IntegerValue
	}
	return 0
}

func (m *StructuredData) GetStringValue() string {
	if x, ok := m.GetValue().(*StructuredData_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *StructuredData) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*StructuredData_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StructuredData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StructuredData_IntegerValue)(nil),
		(*StructuredData_StringValue)(nil),
		(*StructuredData_BooleanValue)(nil),
	}
}

type Record struct {
	Key                  string                     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Blob                 []byte                     `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	BlobSize             int32                      `protobuf:"varint,3,opt,name=blob_size,json=blobSize,proto3" json:"blob_size,omitempty"`
	StucturedData        map[string]*StructuredData `protobuf:"bytes,4,rep,name=stuctured_data,json=stucturedData,proto3" json:"stuctured_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{1}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Record) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

func (m *Record) GetBlobSize() int32 {
	if m != nil {
		return m.BlobSize
	}
	return 0
}

func (m *Record) GetStucturedData() map[string]*StructuredData {
	if m != nil {
		return m.StucturedData
	}
	return nil
}

// Resources for handling generic stores
type StoreOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreOptions) Reset()         { *m = StoreOptions{} }
func (m *StoreOptions) String() string { return proto.CompactTextString(m) }
func (*StoreOptions) ProtoMessage()    {}
func (*StoreOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{2}
}

func (m *StoreOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreOptions.Unmarshal(m, b)
}
func (m *StoreOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreOptions.Marshal(b, m, deterministic)
}
func (m *StoreOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreOptions.Merge(m, src)
}
func (m *StoreOptions) XXX_Size() int {
	return xxx_messageInfo_StoreOptions.Size(m)
}
func (m *StoreOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StoreOptions proto.InternalMessageInfo

type Store struct {
	// ID of this store, assigned by the server when the store is created.
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Options              *StoreOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Store) Reset()         { *m = Store{} }
func (m *Store) String() string { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()    {}
func (*Store) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{3}
}

func (m *Store) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Store.Unmarshal(m, b)
}
func (m *Store) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Store.Marshal(b, m, deterministic)
}
func (m *Store) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Store.Merge(m, src)
}
func (m *Store) XXX_Size() int {
	return xxx_messageInfo_Store.Size(m)
}
func (m *Store) XXX_DiscardUnknown() {
	xxx_messageInfo_Store.DiscardUnknown(m)
}

var xxx_messageInfo_Store proto.InternalMessageInfo

func (m *Store) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Store) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Store) GetOptions() *StoreOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type CreateStoreRequest struct {
	Options              *StoreOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateStoreRequest) Reset()         { *m = CreateStoreRequest{} }
func (m *CreateStoreRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStoreRequest) ProtoMessage()    {}
func (*CreateStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{4}
}

func (m *CreateStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStoreRequest.Unmarshal(m, b)
}
func (m *CreateStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStoreRequest.Marshal(b, m, deterministic)
}
func (m *CreateStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStoreRequest.Merge(m, src)
}
func (m *CreateStoreRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStoreRequest.Size(m)
}
func (m *CreateStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStoreRequest proto.InternalMessageInfo

func (m *CreateStoreRequest) GetOptions() *StoreOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *CreateStoreRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetStoreRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStoreRequest) Reset()         { *m = GetStoreRequest{} }
func (m *GetStoreRequest) String() string { return proto.CompactTextString(m) }
func (*GetStoreRequest) ProtoMessage()    {}
func (*GetStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{5}
}

func (m *GetStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStoreRequest.Unmarshal(m, b)
}
func (m *GetStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStoreRequest.Marshal(b, m, deterministic)
}
func (m *GetStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStoreRequest.Merge(m, src)
}
func (m *GetStoreRequest) XXX_Size() int {
	return xxx_messageInfo_GetStoreRequest.Size(m)
}
func (m *GetStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStoreRequest proto.InternalMessageInfo

func (m *GetStoreRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListStoresRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStoresRequest) Reset()         { *m = ListStoresRequest{} }
func (m *ListStoresRequest) String() string { return proto.CompactTextString(m) }
func (*ListStoresRequest) ProtoMessage()    {}
func (*ListStoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{6}
}

func (m *ListStoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStoresRequest.Unmarshal(m, b)
}
func (m *ListStoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStoresRequest.Marshal(b, m, deterministic)
}
func (m *ListStoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStoresRequest.Merge(m, src)
}
func (m *ListStoresRequest) XXX_Size() int {
	return xxx_messageInfo_ListStoresRequest.Size(m)
}
func (m *ListStoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStoresRequest proto.InternalMessageInfo

type QueryStoreRequest struct {
	StoreId  int64  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Property string `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	// Types that are valid to be assigned to Condition:
	//	*QueryStoreRequest_IntegerValue
	//	*QueryStoreRequest_BooleanValue
	//	*QueryStoreRequest_StringValue
	Condition            isQueryStoreRequest_Condition `protobuf_oneof:"condition"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *QueryStoreRequest) Reset()         { *m = QueryStoreRequest{} }
func (m *QueryStoreRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStoreRequest) ProtoMessage()    {}
func (*QueryStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{7}
}

func (m *QueryStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryStoreRequest.Unmarshal(m, b)
}
func (m *QueryStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryStoreRequest.Marshal(b, m, deterministic)
}
func (m *QueryStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStoreRequest.Merge(m, src)
}
func (m *QueryStoreRequest) XXX_Size() int {
	return xxx_messageInfo_QueryStoreRequest.Size(m)
}
func (m *QueryStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStoreRequest proto.InternalMessageInfo

func (m *QueryStoreRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *QueryStoreRequest) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

type isQueryStoreRequest_Condition interface {
	isQueryStoreRequest_Condition()
}

type QueryStoreRequest_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,3,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type QueryStoreRequest_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,4,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type QueryStoreRequest_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*QueryStoreRequest_IntegerValue) isQueryStoreRequest_Condition() {}

func (*QueryStoreRequest_BooleanValue) isQueryStoreRequest_Condition() {}

func (*QueryStoreRequest_StringValue) isQueryStoreRequest_Condition() {}

func (m *QueryStoreRequest) GetCondition() isQueryStoreRequest_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *QueryStoreRequest) GetIntegerValue() int64 {
	if x, ok := m.GetCondition().(*QueryStoreRequest_IntegerValue); ok {
		return x.IntegerValue
	}
	return 0
}

func (m *QueryStoreRequest) GetBooleanValue() bool {
	if x, ok := m.GetCondition().(*QueryStoreRequest_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *QueryStoreRequest) GetStringValue() string {
	if x, ok := m.GetCondition().(*QueryStoreRequest_StringValue); ok {
		return x.StringValue
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueryStoreRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueryStoreRequest_IntegerValue)(nil),
		(*QueryStoreRequest_BooleanValue)(nil),
		(*QueryStoreRequest_StringValue)(nil),
	}
}

type DeleteStoreRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStoreRequest) Reset()         { *m = DeleteStoreRequest{} }
func (m *DeleteStoreRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStoreRequest) ProtoMessage()    {}
func (*DeleteStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{8}
}

func (m *DeleteStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStoreRequest.Unmarshal(m, b)
}
func (m *DeleteStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStoreRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStoreRequest.Merge(m, src)
}
func (m *DeleteStoreRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStoreRequest.Size(m)
}
func (m *DeleteStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStoreRequest proto.InternalMessageInfo

func (m *DeleteStoreRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateRecordRequest struct {
	StoreId              int64    `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Record               *Record  `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Hint                 Hint     `protobuf:"varint,3,opt,name=hint,proto3,enum=triton.Hint" json:"hint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRecordRequest) Reset()         { *m = CreateRecordRequest{} }
func (m *CreateRecordRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRecordRequest) ProtoMessage()    {}
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{9}
}

func (m *CreateRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecordRequest.Unmarshal(m, b)
}
func (m *CreateRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecordRequest.Marshal(b, m, deterministic)
}
func (m *CreateRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecordRequest.Merge(m, src)
}
func (m *CreateRecordRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRecordRequest.Size(m)
}
func (m *CreateRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecordRequest proto.InternalMessageInfo

func (m *CreateRecordRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *CreateRecordRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *CreateRecordRequest) GetHint() Hint {
	if m != nil {
		return m.Hint
	}
	return Hint_HINT_UNSPECIFIED
}

type GetRecordRequest struct {
	StoreId              int64    `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordRequest) Reset()         { *m = GetRecordRequest{} }
func (m *GetRecordRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecordRequest) ProtoMessage()    {}
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{10}
}

func (m *GetRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordRequest.Unmarshal(m, b)
}
func (m *GetRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordRequest.Marshal(b, m, deterministic)
}
func (m *GetRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordRequest.Merge(m, src)
}
func (m *GetRecordRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecordRequest.Size(m)
}
func (m *GetRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordRequest proto.InternalMessageInfo

func (m *GetRecordRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *GetRecordRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type UpdateRecordRequest struct {
	StoreId              int64    `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Record               *Record  `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	Hint                 Hint     `protobuf:"varint,4,opt,name=hint,proto3,enum=triton.Hint" json:"hint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecordRequest) Reset()         { *m = UpdateRecordRequest{} }
func (m *UpdateRecordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRecordRequest) ProtoMessage()    {}
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{11}
}

func (m *UpdateRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecordRequest.Unmarshal(m, b)
}
func (m *UpdateRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecordRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecordRequest.Merge(m, src)
}
func (m *UpdateRecordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRecordRequest.Size(m)
}
func (m *UpdateRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecordRequest proto.InternalMessageInfo

func (m *UpdateRecordRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *UpdateRecordRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateRecordRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *UpdateRecordRequest) GetHint() Hint {
	if m != nil {
		return m.Hint
	}
	return Hint_HINT_UNSPECIFIED
}

type DeleteRecordRequest struct {
	StoreId              int64    `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecordRequest) Reset()         { *m = DeleteRecordRequest{} }
func (m *DeleteRecordRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRecordRequest) ProtoMessage()    {}
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{12}
}

func (m *DeleteRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecordRequest.Unmarshal(m, b)
}
func (m *DeleteRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecordRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecordRequest.Merge(m, src)
}
func (m *DeleteRecordRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRecordRequest.Size(m)
}
func (m *DeleteRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecordRequest proto.InternalMessageInfo

func (m *DeleteRecordRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *DeleteRecordRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ListStoresResponse struct {
	Stores               []*Store `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStoresResponse) Reset()         { *m = ListStoresResponse{} }
func (m *ListStoresResponse) String() string { return proto.CompactTextString(m) }
func (*ListStoresResponse) ProtoMessage()    {}
func (*ListStoresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{13}
}

func (m *ListStoresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStoresResponse.Unmarshal(m, b)
}
func (m *ListStoresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStoresResponse.Marshal(b, m, deterministic)
}
func (m *ListStoresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStoresResponse.Merge(m, src)
}
func (m *ListStoresResponse) XXX_Size() int {
	return xxx_messageInfo_ListStoresResponse.Size(m)
}
func (m *ListStoresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStoresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStoresResponse proto.InternalMessageInfo

func (m *ListStoresResponse) GetStores() []*Store {
	if m != nil {
		return m.Stores
	}
	return nil
}

func init() {
	proto.RegisterEnum("triton.Hint", Hint_name, Hint_value)
	proto.RegisterType((*StructuredData)(nil), "triton.StructuredData")
	proto.RegisterType((*Record)(nil), "triton.Record")
	proto.RegisterMapType((map[string]*StructuredData)(nil), "triton.Record.StucturedDataEntry")
	proto.RegisterType((*StoreOptions)(nil), "triton.StoreOptions")
	proto.RegisterType((*Store)(nil), "triton.Store")
	proto.RegisterType((*CreateStoreRequest)(nil), "triton.CreateStoreRequest")
	proto.RegisterType((*GetStoreRequest)(nil), "triton.GetStoreRequest")
	proto.RegisterType((*ListStoresRequest)(nil), "triton.ListStoresRequest")
	proto.RegisterType((*QueryStoreRequest)(nil), "triton.QueryStoreRequest")
	proto.RegisterType((*DeleteStoreRequest)(nil), "triton.DeleteStoreRequest")
	proto.RegisterType((*CreateRecordRequest)(nil), "triton.CreateRecordRequest")
	proto.RegisterType((*GetRecordRequest)(nil), "triton.GetRecordRequest")
	proto.RegisterType((*UpdateRecordRequest)(nil), "triton.UpdateRecordRequest")
	proto.RegisterType((*DeleteRecordRequest)(nil), "triton.DeleteRecordRequest")
	proto.RegisterType((*ListStoresResponse)(nil), "triton.ListStoresResponse")
}

func init() {
	proto.RegisterFile("triton.proto", fileDescriptor_33b183c252d47990)
}

var fileDescriptor_33b183c252d47990 = []byte{
	// 893 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4b, 0x6f, 0xe3, 0x54,
	0x14, 0xae, 0x93, 0x34, 0x4d, 0x4e, 0xdc, 0x34, 0x3d, 0x9d, 0x47, 0xeb, 0x82, 0x94, 0xf1, 0x50,
	0x14, 0x15, 0x94, 0x88, 0xb0, 0x41, 0xc3, 0x02, 0xf5, 0x11, 0x9a, 0x68, 0xaa, 0x06, 0x6e, 0xda,
	0x61, 0x80, 0x85, 0xe5, 0xd4, 0x97, 0x62, 0x35, 0xe3, 0x6b, 0xec, 0x9b, 0x4a, 0xe9, 0xa8, 0x1b,
	0xc4, 0x92, 0x1d, 0xff, 0x8a, 0x2d, 0x7f, 0x81, 0x3d, 0x7f, 0x01, 0xdd, 0x87, 0x13, 0x27, 0xce,
	0x8c, 0x82, 0x58, 0xd9, 0xf7, 0xbc, 0xbf, 0x73, 0xbf, 0xcf, 0x06, 0x93, 0x47, 0x3e, 0x67, 0x41,
	0x33, 0x8c, 0x18, 0x67, 0x58, 0x54, 0x27, 0xeb, 0x83, 0x1b, 0xc6, 0x6e, 0x46, 0xb4, 0xe5, 0x86,
	0x7e, 0xcb, 0x0d, 0x02, 0xc6, 0x5d, 0xee, 0xb3, 0x20, 0x56, 0x51, 0xd6, 0xbe, 0xf6, 0xca, 0xd3,
	0x70, 0xfc, 0x53, 0x8b, 0xbe, 0x09, 0xf9, 0x44, 0x39, 0xed, 0xdf, 0x0d, 0xa8, 0x0e, 0x78, 0x34,
	0xbe, 0xe6, 0xe3, 0x88, 0x7a, 0xa7, 0x2e, 0x77, 0xf1, 0x00, 0x36, 0xfd, 0x80, 0xd3, 0x1b, 0x1a,
	0x39, 0x77, 0xee, 0x68, 0x4c, 0x77, 0x8d, 0xba, 0xd1, 0xc8, 0x77, 0xd7, 0x88, 0xa9, 0xcd, 0xaf,
	0x84, 0x15, 0x9f, 0x83, 0x19, 0xf3, 0xc8, 0x0f, 0x6e, 0x74, 0x54, 0xae, 0x6e, 0x34, 0xca, 0xdd,
	0x35, 0x52, 0x51, 0x56, 0x15, 0x74, 0x00, 0x9b, 0x43, 0xc6, 0x46, 0xd4, 0x0d, 0x74, 0x54, 0xbe,
	0x6e, 0x34, 0x4a, 0xa2, 0x96, 0x36, 0xcb, 0xb0, 0xe3, 0x0d, 0x58, 0x97, 0x6e, 0xfb, 0x1f, 0x03,
	0x8a, 0x84, 0x5e, 0xb3, 0xc8, 0xc3, 0x1a, 0xe4, 0x6f, 0xe9, 0x44, 0x36, 0x2f, 0x13, 0xf1, 0x8a,
	0x08, 0x85, 0xe1, 0x88, 0x0d, 0x65, 0x27, 0x93, 0xc8, 0x77, 0xdc, 0x87, 0xb2, 0x78, 0x3a, 0xb1,
	0x7f, 0xaf, 0x8a, 0xaf, 0x93, 0x92, 0x30, 0x0c, 0xfc, 0x7b, 0x8a, 0x5d, 0xa8, 0xc6, 0x5c, 0x43,
	0x73, 0x3c, 0x97, 0xbb, 0xbb, 0x85, 0x7a, 0xbe, 0x51, 0x69, 0x3f, 0x6b, 0xea, 0x35, 0xaa, 0x56,
	0xcd, 0x01, 0x4f, 0xe1, 0xef, 0x04, 0x3c, 0x9a, 0x90, 0xcd, 0x38, 0x6d, 0xb3, 0x5e, 0x03, 0x66,
	0x83, 0x96, 0x8c, 0xf8, 0xa9, 0x06, 0x22, 0x67, 0xac, 0xb4, 0x9f, 0x24, 0x8d, 0xe6, 0x57, 0x4c,
	0x54, 0xd0, 0x8b, 0xdc, 0x17, 0x86, 0x5d, 0x05, 0x73, 0xc0, 0x59, 0x44, 0xfb, 0xa1, 0xbc, 0x33,
	0xfb, 0x47, 0x58, 0x97, 0x67, 0xac, 0x42, 0xce, 0xf7, 0xd4, 0xee, 0x49, 0xce, 0xf7, 0x04, 0xfa,
	0xc0, 0x7d, 0xa3, 0xf7, 0x4c, 0xe4, 0x3b, 0x36, 0x61, 0x83, 0xa9, 0x3c, 0x89, 0xbd, 0xd2, 0x7e,
	0x34, 0x6b, 0x38, 0xab, 0x49, 0x92, 0x20, 0xfb, 0x35, 0xe0, 0x49, 0x44, 0x5d, 0x4e, 0xa5, 0x9b,
	0xd0, 0x5f, 0xc6, 0x34, 0xe6, 0xe9, 0x2a, 0xc6, 0x0a, 0x55, 0x96, 0x4d, 0x62, 0x3f, 0x83, 0xad,
	0x33, 0xca, 0xe7, 0xca, 0x2e, 0x00, 0xb0, 0x77, 0x60, 0xfb, 0xdc, 0x8f, 0x55, 0x4c, 0xac, 0x83,
	0xec, 0x3f, 0x0d, 0xd8, 0xfe, 0x76, 0x4c, 0xa3, 0xc9, 0x5c, 0xea, 0x1e, 0x94, 0x62, 0x71, 0x76,
	0xa6, 0x05, 0x36, 0xe4, 0xb9, 0xe7, 0xa1, 0x05, 0xa5, 0x30, 0x62, 0x21, 0x8d, 0xf8, 0x44, 0x0f,
	0x30, 0x3d, 0x67, 0x99, 0x9b, 0x5f, 0xca, 0xdc, 0x0c, 0x29, 0x0b, 0xcb, 0x48, 0x99, 0x21, 0xf8,
	0xfa, 0x12, 0x82, 0x1f, 0x57, 0xa0, 0x7c, 0xcd, 0x02, 0xcf, 0x17, 0x9b, 0xb1, 0x3f, 0x02, 0x3c,
	0xa5, 0x23, 0xba, 0xb0, 0xde, 0xc5, 0x3d, 0xdc, 0xc3, 0x8e, 0xba, 0x04, 0xc5, 0xbe, 0x15, 0x30,
	0x7f, 0x0c, 0xc5, 0x48, 0xc6, 0x6a, 0x5a, 0x55, 0xe7, 0xf9, 0x4b, 0xb4, 0x17, 0xeb, 0x50, 0xf8,
	0xd9, 0x0f, 0xb8, 0x84, 0x5d, 0x6d, 0x9b, 0x49, 0x54, 0xd7, 0x0f, 0x38, 0x91, 0x1e, 0xfb, 0x2b,
	0xa8, 0x9d, 0x51, 0xbe, 0x72, 0x63, 0x4d, 0xf0, 0xdc, 0x94, 0xe0, 0xe2, 0x7b, 0xb1, 0x73, 0x15,
	0x7a, 0xff, 0x65, 0xfa, 0x4c, 0x91, 0x14, 0x9e, 0xfc, 0x4a, 0x78, 0x0a, 0xef, 0xc4, 0x73, 0x0c,
	0x3b, 0x6a, 0xe3, 0xff, 0x03, 0xd2, 0x97, 0x80, 0x69, 0x5e, 0xc6, 0x21, 0x0b, 0x62, 0x41, 0x92,
	0xa2, 0x4c, 0x11, 0x9a, 0x10, 0xdf, 0x8c, 0xcd, 0x39, 0x4d, 0x10, 0xed, 0x3c, 0xbc, 0x83, 0x82,
	0x18, 0x07, 0x1f, 0x41, 0xad, 0xdb, 0xbb, 0xb8, 0x74, 0xae, 0x2e, 0x06, 0xdf, 0x74, 0x4e, 0x7a,
	0x5f, 0xf7, 0x3a, 0xa7, 0xb5, 0x35, 0xac, 0x81, 0x79, 0xda, 0x77, 0x2e, 0xfa, 0x97, 0xce, 0xc9,
	0xd1, 0x49, 0xb7, 0x53, 0x33, 0x84, 0xa5, 0x77, 0x76, 0xd1, 0x27, 0x1d, 0x6d, 0xc9, 0xe1, 0x1e,
	0x3c, 0x3e, 0x3a, 0xff, 0xee, 0xe8, 0xfb, 0x81, 0x73, 0x35, 0xe8, 0x38, 0xc7, 0x57, 0xe7, 0x2f,
	0x9d, 0xc1, 0x65, 0x9f, 0x74, 0x6a, 0x79, 0xe1, 0xd2, 0xe9, 0x0b, 0xae, 0x42, 0xfb, 0xb7, 0x22,
	0x14, 0x2f, 0xe5, 0x40, 0xd8, 0x87, 0x4a, 0x4a, 0xd4, 0x68, 0x25, 0x83, 0x66, 0x95, 0x6e, 0xcd,
	0x83, 0xb0, 0x1f, 0xff, 0xfa, 0xd7, 0xdf, 0x7f, 0xe4, 0xb6, 0x6c, 0x68, 0xdd, 0x7d, 0xd6, 0x52,
	0x80, 0x5e, 0x18, 0x87, 0xf8, 0x12, 0x4a, 0x89, 0x96, 0xf1, 0x69, 0x92, 0xb1, 0xa0, 0xee, 0xc5,
	0x52, 0x4f, 0x65, 0xa9, 0x6d, 0xdc, 0x9a, 0x95, 0x6a, 0xbd, 0xf5, 0xbd, 0x07, 0x7c, 0x05, 0xe5,
	0xe9, 0x76, 0x71, 0x2f, 0x49, 0xca, 0x7c, 0x08, 0x2c, 0x6b, 0x99, 0x4b, 0xdd, 0x85, 0x8d, 0xb2,
	0xb8, 0x89, 0xa9, 0x39, 0xf1, 0x07, 0xa8, 0xa4, 0xb4, 0x36, 0x43, 0x9d, 0x15, 0xa0, 0xf5, 0xa4,
	0xa9, 0xfe, 0x80, 0xcd, 0xe4, 0x0f, 0xd8, 0xec, 0x88, 0x3f, 0x60, 0x32, 0xf3, 0x61, 0x66, 0x66,
	0x0a, 0x66, 0x5a, 0xa1, 0xb8, 0x3f, 0xbf, 0xd2, 0x39, 0xae, 0x59, 0x0b, 0xe4, 0xb5, 0x1b, 0xb2,
	0xaa, 0x6d, 0x7f, 0x98, 0xae, 0x9a, 0xb0, 0xf1, 0xa1, 0xa5, 0xa8, 0x2d, 0xf7, 0x3c, 0x84, 0xf2,
	0x54, 0x8c, 0xb8, 0x9b, 0x5a, 0xf4, 0xfb, 0x1b, 0x7c, 0x22, 0x1b, 0x1c, 0xe0, 0xf3, 0xf7, 0x36,
	0x68, 0xbd, 0xbd, 0xa5, 0x93, 0x07, 0xbc, 0x05, 0x33, 0x2d, 0xd7, 0x19, 0x94, 0x25, 0x22, 0xce,
	0x74, 0x6a, 0xca, 0x4e, 0x8d, 0xf6, 0x2a, 0x9d, 0x04, 0xa0, 0x10, 0xcc, 0xb4, 0x1a, 0x67, 0xcd,
	0x96, 0x68, 0xf4, 0x9d, 0xb7, 0xa2, 0xe1, 0x1d, 0xae, 0xd2, 0x74, 0x58, 0x94, 0xc9, 0x9f, 0xff,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x02, 0x83, 0x34, 0x18, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TritonClient is the client API for Triton service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TritonClient interface {
	CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*Store, error)
	GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*Store, error)
	ListStore(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error)
	DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*Record, error)
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*Record, error)
	UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*Record, error)
	DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type tritonClient struct {
	cc grpc.ClientConnInterface
}

func NewTritonClient(cc grpc.ClientConnInterface) TritonClient {
	return &tritonClient{cc}
}

func (c *tritonClient) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*Store, error) {
	out := new(Store)
	err := c.cc.Invoke(ctx, "/triton.Triton/CreateStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*Store, error) {
	out := new(Store)
	err := c.cc.Invoke(ctx, "/triton.Triton/GetStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) ListStore(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error) {
	out := new(ListStoresResponse)
	err := c.cc.Invoke(ctx, "/triton.Triton/ListStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/triton.Triton/DeleteStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/triton.Triton/CreateRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/triton.Triton/GetRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/triton.Triton/UpdateRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/triton.Triton/DeleteRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TritonServer is the server API for Triton service.
type TritonServer interface {
	CreateStore(context.Context, *CreateStoreRequest) (*Store, error)
	GetStore(context.Context, *GetStoreRequest) (*Store, error)
	ListStore(context.Context, *ListStoresRequest) (*ListStoresResponse, error)
	DeleteStore(context.Context, *DeleteStoreRequest) (*empty.Empty, error)
	CreateRecord(context.Context, *CreateRecordRequest) (*Record, error)
	GetRecord(context.Context, *GetRecordRequest) (*Record, error)
	UpdateRecord(context.Context, *UpdateRecordRequest) (*Record, error)
	DeleteRecord(context.Context, *DeleteRecordRequest) (*empty.Empty, error)
}

// UnimplementedTritonServer can be embedded to have forward compatible implementations.
type UnimplementedTritonServer struct {
}

func (*UnimplementedTritonServer) CreateStore(ctx context.Context, req *CreateStoreRequest) (*Store, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStore not implemented")
}
func (*UnimplementedTritonServer) GetStore(ctx context.Context, req *GetStoreRequest) (*Store, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStore not implemented")
}
func (*UnimplementedTritonServer) ListStore(ctx context.Context, req *ListStoresRequest) (*ListStoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStore not implemented")
}
func (*UnimplementedTritonServer) DeleteStore(ctx context.Context, req *DeleteStoreRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStore not implemented")
}
func (*UnimplementedTritonServer) CreateRecord(ctx context.Context, req *CreateRecordRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecord not implemented")
}
func (*UnimplementedTritonServer) GetRecord(ctx context.Context, req *GetRecordRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (*UnimplementedTritonServer) UpdateRecord(ctx context.Context, req *UpdateRecordRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRecord not implemented")
}
func (*UnimplementedTritonServer) DeleteRecord(ctx context.Context, req *DeleteRecordRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRecord not implemented")
}

func RegisterTritonServer(s *grpc.Server, srv TritonServer) {
	s.RegisterService(&_Triton_serviceDesc, srv)
}

func _Triton_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/CreateStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).CreateStore(ctx, req.(*CreateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_GetStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).GetStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/GetStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).GetStore(ctx, req.(*GetStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_ListStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).ListStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/ListStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).ListStore(ctx, req.(*ListStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/DeleteStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).DeleteStore(ctx, req.(*DeleteStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_CreateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).CreateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/CreateRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).CreateRecord(ctx, req.(*CreateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/GetRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_UpdateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).UpdateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/UpdateRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).UpdateRecord(ctx, req.(*UpdateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_DeleteRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).DeleteRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/DeleteRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).DeleteRecord(ctx, req.(*DeleteRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Triton_serviceDesc = grpc.ServiceDesc{
	ServiceName: "triton.Triton",
	HandlerType: (*TritonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStore",
			Handler:    _Triton_CreateStore_Handler,
		},
		{
			MethodName: "GetStore",
			Handler:    _Triton_GetStore_Handler,
		},
		{
			MethodName: "ListStore",
			Handler:    _Triton_ListStore_Handler,
		},
		{
			MethodName: "DeleteStore",
			Handler:    _Triton_DeleteStore_Handler,
		},
		{
			MethodName: "CreateRecord",
			Handler:    _Triton_CreateRecord_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _Triton_GetRecord_Handler,
		},
		{
			MethodName: "UpdateRecord",
			Handler:    _Triton_UpdateRecord_Handler,
		},
		{
			MethodName: "DeleteRecord",
			Handler:    _Triton_DeleteRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "triton.proto",
}
