// Code generated by protoc-gen-go. DO NOT EDIT.
// source: triton.proto

package triton

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hint int32

const (
	// Unspecified. This value must not be used.
	Hint_HINT_UNSPECIFIED      Hint = 0
	Hint_DO_NOT_CACHE          Hint = 1
	Hint_IGNORE_CACHE          Hint = 2
	Hint_ALWAYS_USE_BULK_STORE Hint = 3
	Hint_DO_NOT_USE_BULK_STORE Hint = 4
)

var Hint_name = map[int32]string{
	0: "HINT_UNSPECIFIED",
	1: "DO_NOT_CACHE",
	2: "IGNORE_CACHE",
	3: "ALWAYS_USE_BULK_STORE",
	4: "DO_NOT_USE_BULK_STORE",
}

var Hint_value = map[string]int32{
	"HINT_UNSPECIFIED":      0,
	"DO_NOT_CACHE":          1,
	"IGNORE_CACHE":          2,
	"ALWAYS_USE_BULK_STORE": 3,
	"DO_NOT_USE_BULK_STORE": 4,
}

func (x Hint) String() string {
	return proto.EnumName(Hint_name, int32(x))
}

func (Hint) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{0}
}

type StructuredData struct {
	// Types that are valid to be assigned to Value:
	//	*StructuredData_IntegerValue
	//	*StructuredData_StringValue
	//	*StructuredData_BooleanValue
	Value                isStructuredData_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StructuredData) Reset()         { *m = StructuredData{} }
func (m *StructuredData) String() string { return proto.CompactTextString(m) }
func (*StructuredData) ProtoMessage()    {}
func (*StructuredData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{0}
}

func (m *StructuredData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructuredData.Unmarshal(m, b)
}
func (m *StructuredData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructuredData.Marshal(b, m, deterministic)
}
func (m *StructuredData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructuredData.Merge(m, src)
}
func (m *StructuredData) XXX_Size() int {
	return xxx_messageInfo_StructuredData.Size(m)
}
func (m *StructuredData) XXX_DiscardUnknown() {
	xxx_messageInfo_StructuredData.DiscardUnknown(m)
}

var xxx_messageInfo_StructuredData proto.InternalMessageInfo

type isStructuredData_Value interface {
	isStructuredData_Value()
}

type StructuredData_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,1,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type StructuredData_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type StructuredData_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,3,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

func (*StructuredData_IntegerValue) isStructuredData_Value() {}

func (*StructuredData_StringValue) isStructuredData_Value() {}

func (*StructuredData_BooleanValue) isStructuredData_Value() {}

func (m *StructuredData) GetValue() isStructuredData_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *StructuredData) GetIntegerValue() int64 {
	if x, ok := m.GetValue().(*StructuredData_IntegerValue); ok {
		return x.IntegerValue
	}
	return 0
}

func (m *StructuredData) GetStringValue() string {
	if x, ok := m.GetValue().(*StructuredData_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *StructuredData) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*StructuredData_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StructuredData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StructuredData_IntegerValue)(nil),
		(*StructuredData_StringValue)(nil),
		(*StructuredData_BooleanValue)(nil),
	}
}

type KeyValue struct {
	Key                  string                     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Blob                 []byte                     `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	BlobSize             int32                      `protobuf:"varint,3,opt,name=blob_size,json=blobSize,proto3" json:"blob_size,omitempty"`
	StucturedData        map[string]*StructuredData `protobuf:"bytes,4,rep,name=stuctured_data,json=stucturedData,proto3" json:"stuctured_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{1}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

func (m *KeyValue) GetBlobSize() int32 {
	if m != nil {
		return m.BlobSize
	}
	return 0
}

func (m *KeyValue) GetStucturedData() map[string]*StructuredData {
	if m != nil {
		return m.StucturedData
	}
	return nil
}

// Resources for handling generic stores
type StoreOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreOptions) Reset()         { *m = StoreOptions{} }
func (m *StoreOptions) String() string { return proto.CompactTextString(m) }
func (*StoreOptions) ProtoMessage()    {}
func (*StoreOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{2}
}

func (m *StoreOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreOptions.Unmarshal(m, b)
}
func (m *StoreOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreOptions.Marshal(b, m, deterministic)
}
func (m *StoreOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreOptions.Merge(m, src)
}
func (m *StoreOptions) XXX_Size() int {
	return xxx_messageInfo_StoreOptions.Size(m)
}
func (m *StoreOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StoreOptions proto.InternalMessageInfo

type Store struct {
	// ID of this store, assigned by the server when the store is created.
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Options              *StoreOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Store) Reset()         { *m = Store{} }
func (m *Store) String() string { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()    {}
func (*Store) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{3}
}

func (m *Store) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Store.Unmarshal(m, b)
}
func (m *Store) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Store.Marshal(b, m, deterministic)
}
func (m *Store) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Store.Merge(m, src)
}
func (m *Store) XXX_Size() int {
	return xxx_messageInfo_Store.Size(m)
}
func (m *Store) XXX_DiscardUnknown() {
	xxx_messageInfo_Store.DiscardUnknown(m)
}

var xxx_messageInfo_Store proto.InternalMessageInfo

func (m *Store) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Store) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Store) GetOptions() *StoreOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type CreateStoreRequest struct {
	Options              *StoreOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateStoreRequest) Reset()         { *m = CreateStoreRequest{} }
func (m *CreateStoreRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStoreRequest) ProtoMessage()    {}
func (*CreateStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{4}
}

func (m *CreateStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStoreRequest.Unmarshal(m, b)
}
func (m *CreateStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStoreRequest.Marshal(b, m, deterministic)
}
func (m *CreateStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStoreRequest.Merge(m, src)
}
func (m *CreateStoreRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStoreRequest.Size(m)
}
func (m *CreateStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStoreRequest proto.InternalMessageInfo

func (m *CreateStoreRequest) GetOptions() *StoreOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *CreateStoreRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetStoreRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStoreRequest) Reset()         { *m = GetStoreRequest{} }
func (m *GetStoreRequest) String() string { return proto.CompactTextString(m) }
func (*GetStoreRequest) ProtoMessage()    {}
func (*GetStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{5}
}

func (m *GetStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStoreRequest.Unmarshal(m, b)
}
func (m *GetStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStoreRequest.Marshal(b, m, deterministic)
}
func (m *GetStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStoreRequest.Merge(m, src)
}
func (m *GetStoreRequest) XXX_Size() int {
	return xxx_messageInfo_GetStoreRequest.Size(m)
}
func (m *GetStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStoreRequest proto.InternalMessageInfo

func (m *GetStoreRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListStoresRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStoresRequest) Reset()         { *m = ListStoresRequest{} }
func (m *ListStoresRequest) String() string { return proto.CompactTextString(m) }
func (*ListStoresRequest) ProtoMessage()    {}
func (*ListStoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{6}
}

func (m *ListStoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStoresRequest.Unmarshal(m, b)
}
func (m *ListStoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStoresRequest.Marshal(b, m, deterministic)
}
func (m *ListStoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStoresRequest.Merge(m, src)
}
func (m *ListStoresRequest) XXX_Size() int {
	return xxx_messageInfo_ListStoresRequest.Size(m)
}
func (m *ListStoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStoresRequest proto.InternalMessageInfo

type QueryStoreRequest struct {
	StoreId  int64  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Property string `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	// Types that are valid to be assigned to Condition:
	//	*QueryStoreRequest_IntegerValue
	//	*QueryStoreRequest_BooleanValue
	//	*QueryStoreRequest_StringValue
	Condition            isQueryStoreRequest_Condition `protobuf_oneof:"condition"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *QueryStoreRequest) Reset()         { *m = QueryStoreRequest{} }
func (m *QueryStoreRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStoreRequest) ProtoMessage()    {}
func (*QueryStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{7}
}

func (m *QueryStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryStoreRequest.Unmarshal(m, b)
}
func (m *QueryStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryStoreRequest.Marshal(b, m, deterministic)
}
func (m *QueryStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStoreRequest.Merge(m, src)
}
func (m *QueryStoreRequest) XXX_Size() int {
	return xxx_messageInfo_QueryStoreRequest.Size(m)
}
func (m *QueryStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStoreRequest proto.InternalMessageInfo

func (m *QueryStoreRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *QueryStoreRequest) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

type isQueryStoreRequest_Condition interface {
	isQueryStoreRequest_Condition()
}

type QueryStoreRequest_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,3,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type QueryStoreRequest_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,4,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type QueryStoreRequest_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*QueryStoreRequest_IntegerValue) isQueryStoreRequest_Condition() {}

func (*QueryStoreRequest_BooleanValue) isQueryStoreRequest_Condition() {}

func (*QueryStoreRequest_StringValue) isQueryStoreRequest_Condition() {}

func (m *QueryStoreRequest) GetCondition() isQueryStoreRequest_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *QueryStoreRequest) GetIntegerValue() int64 {
	if x, ok := m.GetCondition().(*QueryStoreRequest_IntegerValue); ok {
		return x.IntegerValue
	}
	return 0
}

func (m *QueryStoreRequest) GetBooleanValue() bool {
	if x, ok := m.GetCondition().(*QueryStoreRequest_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *QueryStoreRequest) GetStringValue() string {
	if x, ok := m.GetCondition().(*QueryStoreRequest_StringValue); ok {
		return x.StringValue
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueryStoreRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueryStoreRequest_IntegerValue)(nil),
		(*QueryStoreRequest_BooleanValue)(nil),
		(*QueryStoreRequest_StringValue)(nil),
	}
}

type DeleteStoreRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStoreRequest) Reset()         { *m = DeleteStoreRequest{} }
func (m *DeleteStoreRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStoreRequest) ProtoMessage()    {}
func (*DeleteStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{8}
}

func (m *DeleteStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStoreRequest.Unmarshal(m, b)
}
func (m *DeleteStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStoreRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStoreRequest.Merge(m, src)
}
func (m *DeleteStoreRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStoreRequest.Size(m)
}
func (m *DeleteStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStoreRequest proto.InternalMessageInfo

func (m *DeleteStoreRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateValueRequest struct {
	StoreId              int64     `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	KeyValue             *KeyValue `protobuf:"bytes,2,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	Hint                 Hint      `protobuf:"varint,3,opt,name=hint,proto3,enum=triton.Hint" json:"hint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateValueRequest) Reset()         { *m = CreateValueRequest{} }
func (m *CreateValueRequest) String() string { return proto.CompactTextString(m) }
func (*CreateValueRequest) ProtoMessage()    {}
func (*CreateValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{9}
}

func (m *CreateValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateValueRequest.Unmarshal(m, b)
}
func (m *CreateValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateValueRequest.Marshal(b, m, deterministic)
}
func (m *CreateValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateValueRequest.Merge(m, src)
}
func (m *CreateValueRequest) XXX_Size() int {
	return xxx_messageInfo_CreateValueRequest.Size(m)
}
func (m *CreateValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateValueRequest proto.InternalMessageInfo

func (m *CreateValueRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *CreateValueRequest) GetKeyValue() *KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

func (m *CreateValueRequest) GetHint() Hint {
	if m != nil {
		return m.Hint
	}
	return Hint_HINT_UNSPECIFIED
}

type GetValueRequest struct {
	StoreId              int64    `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueRequest) Reset()         { *m = GetValueRequest{} }
func (m *GetValueRequest) String() string { return proto.CompactTextString(m) }
func (*GetValueRequest) ProtoMessage()    {}
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{10}
}

func (m *GetValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueRequest.Unmarshal(m, b)
}
func (m *GetValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueRequest.Marshal(b, m, deterministic)
}
func (m *GetValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueRequest.Merge(m, src)
}
func (m *GetValueRequest) XXX_Size() int {
	return xxx_messageInfo_GetValueRequest.Size(m)
}
func (m *GetValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueRequest proto.InternalMessageInfo

func (m *GetValueRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *GetValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type UpdateValueRequest struct {
	StoreId              int64     `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Key                  string    `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	KeyValue             *KeyValue `protobuf:"bytes,3,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	Hint                 Hint      `protobuf:"varint,4,opt,name=hint,proto3,enum=triton.Hint" json:"hint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateValueRequest) Reset()         { *m = UpdateValueRequest{} }
func (m *UpdateValueRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateValueRequest) ProtoMessage()    {}
func (*UpdateValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{11}
}

func (m *UpdateValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateValueRequest.Unmarshal(m, b)
}
func (m *UpdateValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateValueRequest.Marshal(b, m, deterministic)
}
func (m *UpdateValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateValueRequest.Merge(m, src)
}
func (m *UpdateValueRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateValueRequest.Size(m)
}
func (m *UpdateValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateValueRequest proto.InternalMessageInfo

func (m *UpdateValueRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *UpdateValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateValueRequest) GetKeyValue() *KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

func (m *UpdateValueRequest) GetHint() Hint {
	if m != nil {
		return m.Hint
	}
	return Hint_HINT_UNSPECIFIED
}

type DeleteValueRequest struct {
	StoreId              int64    `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteValueRequest) Reset()         { *m = DeleteValueRequest{} }
func (m *DeleteValueRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteValueRequest) ProtoMessage()    {}
func (*DeleteValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{12}
}

func (m *DeleteValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteValueRequest.Unmarshal(m, b)
}
func (m *DeleteValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteValueRequest.Marshal(b, m, deterministic)
}
func (m *DeleteValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteValueRequest.Merge(m, src)
}
func (m *DeleteValueRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteValueRequest.Size(m)
}
func (m *DeleteValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteValueRequest proto.InternalMessageInfo

func (m *DeleteValueRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *DeleteValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ListStoresResponse struct {
	Stores               []*Store `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStoresResponse) Reset()         { *m = ListStoresResponse{} }
func (m *ListStoresResponse) String() string { return proto.CompactTextString(m) }
func (*ListStoresResponse) ProtoMessage()    {}
func (*ListStoresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{13}
}

func (m *ListStoresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStoresResponse.Unmarshal(m, b)
}
func (m *ListStoresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStoresResponse.Marshal(b, m, deterministic)
}
func (m *ListStoresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStoresResponse.Merge(m, src)
}
func (m *ListStoresResponse) XXX_Size() int {
	return xxx_messageInfo_ListStoresResponse.Size(m)
}
func (m *ListStoresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStoresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStoresResponse proto.InternalMessageInfo

func (m *ListStoresResponse) GetStores() []*Store {
	if m != nil {
		return m.Stores
	}
	return nil
}

type GetValueResponse struct {
	KeyValue             *KeyValue `protobuf:"bytes,1,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetValueResponse) Reset()         { *m = GetValueResponse{} }
func (m *GetValueResponse) String() string { return proto.CompactTextString(m) }
func (*GetValueResponse) ProtoMessage()    {}
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33b183c252d47990, []int{14}
}

func (m *GetValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueResponse.Unmarshal(m, b)
}
func (m *GetValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueResponse.Marshal(b, m, deterministic)
}
func (m *GetValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueResponse.Merge(m, src)
}
func (m *GetValueResponse) XXX_Size() int {
	return xxx_messageInfo_GetValueResponse.Size(m)
}
func (m *GetValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueResponse proto.InternalMessageInfo

func (m *GetValueResponse) GetKeyValue() *KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

func init() {
	proto.RegisterEnum("triton.Hint", Hint_name, Hint_value)
	proto.RegisterType((*StructuredData)(nil), "triton.StructuredData")
	proto.RegisterType((*KeyValue)(nil), "triton.KeyValue")
	proto.RegisterMapType((map[string]*StructuredData)(nil), "triton.KeyValue.StucturedDataEntry")
	proto.RegisterType((*StoreOptions)(nil), "triton.StoreOptions")
	proto.RegisterType((*Store)(nil), "triton.Store")
	proto.RegisterType((*CreateStoreRequest)(nil), "triton.CreateStoreRequest")
	proto.RegisterType((*GetStoreRequest)(nil), "triton.GetStoreRequest")
	proto.RegisterType((*ListStoresRequest)(nil), "triton.ListStoresRequest")
	proto.RegisterType((*QueryStoreRequest)(nil), "triton.QueryStoreRequest")
	proto.RegisterType((*DeleteStoreRequest)(nil), "triton.DeleteStoreRequest")
	proto.RegisterType((*CreateValueRequest)(nil), "triton.CreateValueRequest")
	proto.RegisterType((*GetValueRequest)(nil), "triton.GetValueRequest")
	proto.RegisterType((*UpdateValueRequest)(nil), "triton.UpdateValueRequest")
	proto.RegisterType((*DeleteValueRequest)(nil), "triton.DeleteValueRequest")
	proto.RegisterType((*ListStoresResponse)(nil), "triton.ListStoresResponse")
	proto.RegisterType((*GetValueResponse)(nil), "triton.GetValueResponse")
}

func init() {
	proto.RegisterFile("triton.proto", fileDescriptor_33b183c252d47990)
}

var fileDescriptor_33b183c252d47990 = []byte{
	// 907 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5d, 0x6f, 0x1b, 0x45,
	0x14, 0xcd, 0xfa, 0x23, 0xb1, 0xaf, 0x1d, 0xc7, 0x19, 0xfa, 0x95, 0x6d, 0x1f, 0xdc, 0x69, 0xab,
	0x46, 0x16, 0xb5, 0x85, 0x79, 0x41, 0x45, 0x42, 0x72, 0x12, 0x53, 0x9b, 0x44, 0x31, 0xcc, 0x26,
	0xa5, 0xc0, 0xc3, 0x6a, 0xdd, 0x1d, 0xc2, 0x12, 0x67, 0x77, 0xd9, 0x1d, 0x47, 0xda, 0x56, 0x91,
	0x10, 0xcf, 0x3c, 0xc1, 0xbf, 0xe2, 0x95, 0xbf, 0xc0, 0x3f, 0xe0, 0x1d, 0xa1, 0xf9, 0x8a, 0xd7,
	0xbb, 0x2e, 0x31, 0x7d, 0xb2, 0x67, 0xee, 0xbd, 0xe7, 0xde, 0x73, 0xe6, 0xcc, 0x2c, 0xd4, 0x59,
	0xe4, 0xb1, 0xc0, 0xef, 0x84, 0x51, 0xc0, 0x02, 0xb4, 0x2e, 0x57, 0xe6, 0x83, 0xb3, 0x20, 0x38,
	0x9b, 0xd2, 0xae, 0x13, 0x7a, 0x5d, 0xc7, 0xf7, 0x03, 0xe6, 0x30, 0x2f, 0xf0, 0x63, 0x99, 0x65,
	0xde, 0x57, 0x51, 0xb1, 0x9a, 0xcc, 0xbe, 0xef, 0xd2, 0x8b, 0x90, 0x25, 0x32, 0x88, 0x7f, 0x35,
	0xa0, 0x61, 0xb1, 0x68, 0xf6, 0x9a, 0xcd, 0x22, 0xea, 0x1e, 0x38, 0xcc, 0x41, 0x4f, 0x60, 0xd3,
	0xf3, 0x19, 0x3d, 0xa3, 0x91, 0x7d, 0xe9, 0x4c, 0x67, 0xf4, 0x9e, 0xd1, 0x32, 0x76, 0x8b, 0xc3,
	0x35, 0x52, 0x57, 0xdb, 0x2f, 0xf9, 0x2e, 0x7a, 0x04, 0xf5, 0x98, 0x45, 0x9e, 0x7f, 0xa6, 0xb2,
	0x0a, 0x2d, 0x63, 0xb7, 0x3a, 0x5c, 0x23, 0x35, 0xb9, 0x2b, 0x93, 0x9e, 0xc0, 0xe6, 0x24, 0x08,
	0xa6, 0xd4, 0xf1, 0x55, 0x56, 0xb1, 0x65, 0xec, 0x56, 0x38, 0x96, 0xda, 0x16, 0x69, 0x7b, 0x1b,
	0x50, 0x16, 0x61, 0xfc, 0xb7, 0x01, 0x95, 0x43, 0x9a, 0xc8, 0xe2, 0x26, 0x14, 0xcf, 0x69, 0x22,
	0xda, 0x57, 0x09, 0xff, 0x8b, 0x10, 0x94, 0x26, 0xd3, 0x60, 0x22, 0x7a, 0xd5, 0x89, 0xf8, 0x8f,
	0xee, 0x43, 0x95, 0xff, 0xda, 0xb1, 0xf7, 0x46, 0xc2, 0x97, 0x49, 0x85, 0x6f, 0x58, 0xde, 0x1b,
	0x8a, 0xbe, 0x80, 0x46, 0xcc, 0x14, 0x39, 0xdb, 0x75, 0x98, 0x73, 0xaf, 0xd4, 0x2a, 0xee, 0xd6,
	0x7a, 0x8f, 0x3a, 0x4a, 0x48, 0xdd, 0xac, 0x63, 0xb1, 0x94, 0x06, 0x03, 0x9f, 0x45, 0x09, 0xd9,
	0x8c, 0xd3, 0x7b, 0xe6, 0x2b, 0x40, 0xf9, 0xa4, 0x25, 0x43, 0x7e, 0xa8, 0xc8, 0x88, 0x29, 0x6b,
	0xbd, 0x3b, 0xba, 0xd5, 0xa2, 0xcc, 0x44, 0x26, 0x3d, 0x2f, 0x7c, 0x62, 0xe0, 0x06, 0xd4, 0x2d,
	0x16, 0x44, 0x74, 0x1c, 0x8a, 0x73, 0xc3, 0xdf, 0x41, 0x59, 0xac, 0x51, 0x03, 0x0a, 0x9e, 0x2b,
	0xf5, 0x27, 0x05, 0xcf, 0xe5, 0xfc, 0x7d, 0xe7, 0x42, 0x69, 0x4d, 0xc4, 0x7f, 0xd4, 0x81, 0x8d,
	0x40, 0xd6, 0x09, 0xf6, 0xb5, 0xde, 0xad, 0x79, 0xc3, 0x39, 0x26, 0xd1, 0x49, 0xf8, 0x15, 0xa0,
	0xfd, 0x88, 0x3a, 0x8c, 0x8a, 0x30, 0xa1, 0x3f, 0xcd, 0x68, 0xcc, 0xd2, 0x28, 0xc6, 0x0a, 0x28,
	0xcb, 0x26, 0xc1, 0x0f, 0x61, 0xeb, 0x05, 0x65, 0x0b, 0xb0, 0x19, 0x02, 0xf8, 0x03, 0xd8, 0x3e,
	0xf2, 0x62, 0x99, 0x13, 0xab, 0x24, 0xfc, 0x87, 0x01, 0xdb, 0x5f, 0xcd, 0x68, 0x94, 0x2c, 0x94,
	0xee, 0x40, 0x25, 0xe6, 0x6b, 0xfb, 0x1a, 0x60, 0x43, 0xac, 0x47, 0x2e, 0x32, 0xa1, 0x12, 0x46,
	0x41, 0x48, 0x23, 0x96, 0xa8, 0x01, 0xae, 0xd7, 0x79, 0xf7, 0x16, 0x97, 0xba, 0x37, 0x67, 0xcc,
	0xd2, 0x32, 0x63, 0xe6, 0x4c, 0x5e, 0x5e, 0x62, 0xf2, 0xbd, 0x1a, 0x54, 0x5f, 0x07, 0xbe, 0xeb,
	0x71, 0x65, 0xf0, 0x63, 0x40, 0x07, 0x74, 0x4a, 0x33, 0xf2, 0x66, 0x75, 0xf8, 0xd9, 0xd0, 0xa7,
	0x20, 0x20, 0x56, 0xe0, 0xfc, 0x0c, 0xaa, 0xe7, 0x34, 0xb1, 0xd3, 0xce, 0x6a, 0x66, 0x4d, 0x4c,
	0x2a, 0xe7, 0xfa, 0xee, 0xb4, 0xa0, 0xf4, 0x83, 0xe7, 0x33, 0xc1, 0xbe, 0xd1, 0xab, 0xeb, 0xcc,
	0xa1, 0xe7, 0x33, 0x22, 0x22, 0xf8, 0x33, 0x71, 0x5a, 0xab, 0xb6, 0x57, 0x36, 0x2f, 0x5c, 0xdb,
	0x1c, 0xff, 0x66, 0x00, 0x3a, 0x0d, 0xdd, 0xff, 0x41, 0x21, 0x87, 0xb1, 0x48, 0xaa, 0xb8, 0x32,
	0xa9, 0xd2, 0x3b, 0x49, 0xf5, 0xb5, 0xfa, 0xef, 0xcf, 0xeb, 0x53, 0x40, 0x69, 0x8b, 0xc6, 0x61,
	0xe0, 0xc7, 0xdc, 0x2f, 0xeb, 0xa2, 0x84, 0x5f, 0x0f, 0xfe, 0x80, 0x6c, 0x2e, 0x5c, 0x0f, 0xa2,
	0x82, 0xb8, 0x0f, 0xcd, 0xb9, 0xa8, 0xaa, 0x74, 0x81, 0xa4, 0x71, 0x13, 0xc9, 0xf6, 0x25, 0x94,
	0x38, 0x21, 0x74, 0x0b, 0x9a, 0xc3, 0xd1, 0xf1, 0x89, 0x7d, 0x7a, 0x6c, 0x7d, 0x39, 0xd8, 0x1f,
	0x7d, 0x3e, 0x1a, 0x1c, 0x34, 0xd7, 0x50, 0x13, 0xea, 0x07, 0x63, 0xfb, 0x78, 0x7c, 0x62, 0xef,
	0xf7, 0xf7, 0x87, 0x83, 0xa6, 0xc1, 0x77, 0x46, 0x2f, 0x8e, 0xc7, 0x64, 0xa0, 0x76, 0x0a, 0x68,
	0x07, 0x6e, 0xf7, 0x8f, 0xbe, 0xee, 0x7f, 0x63, 0xd9, 0xa7, 0xd6, 0xc0, 0xde, 0x3b, 0x3d, 0x3a,
	0xb4, 0xad, 0x93, 0x31, 0x19, 0x34, 0x8b, 0x3c, 0xa4, 0xca, 0x33, 0xa1, 0x52, 0xef, 0x9f, 0x32,
	0xac, 0x9f, 0x88, 0xa9, 0xd0, 0x18, 0x6a, 0xa9, 0x27, 0x02, 0x99, 0x7a, 0xda, 0xfc, 0xbb, 0x61,
	0x2e, 0xea, 0x80, 0x6f, 0xff, 0xf2, 0xe7, 0x5f, 0xbf, 0x17, 0xb6, 0x4c, 0xe8, 0x5e, 0x7e, 0xd4,
	0x95, 0x9a, 0x3c, 0x37, 0xda, 0xe8, 0x10, 0x2a, 0xfa, 0x65, 0x40, 0x77, 0x75, 0x45, 0xe6, 0xad,
	0xc8, 0x42, 0xdd, 0x15, 0x50, 0xdb, 0x68, 0x6b, 0x0e, 0xd5, 0x7d, 0xeb, 0xb9, 0x57, 0xe8, 0x25,
	0x54, 0xaf, 0x0f, 0x08, 0xed, 0xe8, 0xa2, 0xdc, 0xb3, 0x62, 0x9a, 0xcb, 0x42, 0xf2, 0x4c, 0x30,
	0x12, 0xe0, 0x75, 0x94, 0x9a, 0x13, 0x7d, 0x0b, 0xb5, 0xd4, 0xcd, 0x9d, 0xb3, 0xce, 0x5f, 0x67,
	0xf3, 0x4e, 0x47, 0x7e, 0x53, 0x3b, 0xfa, 0x9b, 0xda, 0x19, 0xf0, 0x6f, 0xaa, 0x9e, 0xb9, 0x9d,
	0x9b, 0xd9, 0xd5, 0x8a, 0x4a, 0x23, 0x67, 0x14, 0x4d, 0x9b, 0xd5, 0xcc, 0x79, 0x03, 0x3f, 0x15,
	0xa8, 0x0f, 0xcd, 0x07, 0x69, 0x54, 0x6d, 0xe8, 0xab, 0xae, 0x30, 0x96, 0x90, 0xd9, 0x11, 0x32,
	0xcb, 0x16, 0x69, 0x99, 0x6f, 0xc0, 0x6f, 0x0b, 0xfc, 0xc7, 0x08, 0xff, 0x17, 0x7e, 0xf7, 0xed,
	0x39, 0x4d, 0xae, 0xd0, 0x8f, 0x50, 0x4b, 0x5d, 0xfa, 0x39, 0x91, 0xfc, 0x4b, 0xb0, 0xa4, 0xd1,
	0x33, 0xd1, 0xe8, 0x69, 0x6f, 0x85, 0x46, 0x9c, 0xce, 0x85, 0x3e, 0x90, 0x4c, 0xaf, 0xfc, 0x0d,
	0x7f, 0xe7, 0x81, 0x28, 0x6a, 0xed, 0x15, 0x3a, 0x4e, 0xd6, 0x45, 0xed, 0xc7, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x7a, 0xe1, 0x04, 0xbf, 0x64, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TritonClient is the client API for Triton service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TritonClient interface {
	CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*Store, error)
	GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*Store, error)
	ListStore(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error)
	DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateValue(ctx context.Context, in *CreateValueRequest, opts ...grpc.CallOption) (*KeyValue, error)
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*KeyValue, error)
	UpdateValue(ctx context.Context, in *UpdateValueRequest, opts ...grpc.CallOption) (*KeyValue, error)
	DeleteValue(ctx context.Context, in *DeleteValueRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type tritonClient struct {
	cc grpc.ClientConnInterface
}

func NewTritonClient(cc grpc.ClientConnInterface) TritonClient {
	return &tritonClient{cc}
}

func (c *tritonClient) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*Store, error) {
	out := new(Store)
	err := c.cc.Invoke(ctx, "/triton.Triton/CreateStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*Store, error) {
	out := new(Store)
	err := c.cc.Invoke(ctx, "/triton.Triton/GetStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) ListStore(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error) {
	out := new(ListStoresResponse)
	err := c.cc.Invoke(ctx, "/triton.Triton/ListStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/triton.Triton/DeleteStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) CreateValue(ctx context.Context, in *CreateValueRequest, opts ...grpc.CallOption) (*KeyValue, error) {
	out := new(KeyValue)
	err := c.cc.Invoke(ctx, "/triton.Triton/CreateValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*KeyValue, error) {
	out := new(KeyValue)
	err := c.cc.Invoke(ctx, "/triton.Triton/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) UpdateValue(ctx context.Context, in *UpdateValueRequest, opts ...grpc.CallOption) (*KeyValue, error) {
	out := new(KeyValue)
	err := c.cc.Invoke(ctx, "/triton.Triton/UpdateValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tritonClient) DeleteValue(ctx context.Context, in *DeleteValueRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/triton.Triton/DeleteValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TritonServer is the server API for Triton service.
type TritonServer interface {
	CreateStore(context.Context, *CreateStoreRequest) (*Store, error)
	GetStore(context.Context, *GetStoreRequest) (*Store, error)
	ListStore(context.Context, *ListStoresRequest) (*ListStoresResponse, error)
	DeleteStore(context.Context, *DeleteStoreRequest) (*empty.Empty, error)
	CreateValue(context.Context, *CreateValueRequest) (*KeyValue, error)
	GetValue(context.Context, *GetValueRequest) (*KeyValue, error)
	UpdateValue(context.Context, *UpdateValueRequest) (*KeyValue, error)
	DeleteValue(context.Context, *DeleteValueRequest) (*empty.Empty, error)
}

// UnimplementedTritonServer can be embedded to have forward compatible implementations.
type UnimplementedTritonServer struct {
}

func (*UnimplementedTritonServer) CreateStore(ctx context.Context, req *CreateStoreRequest) (*Store, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStore not implemented")
}
func (*UnimplementedTritonServer) GetStore(ctx context.Context, req *GetStoreRequest) (*Store, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStore not implemented")
}
func (*UnimplementedTritonServer) ListStore(ctx context.Context, req *ListStoresRequest) (*ListStoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStore not implemented")
}
func (*UnimplementedTritonServer) DeleteStore(ctx context.Context, req *DeleteStoreRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStore not implemented")
}
func (*UnimplementedTritonServer) CreateValue(ctx context.Context, req *CreateValueRequest) (*KeyValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateValue not implemented")
}
func (*UnimplementedTritonServer) GetValue(ctx context.Context, req *GetValueRequest) (*KeyValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (*UnimplementedTritonServer) UpdateValue(ctx context.Context, req *UpdateValueRequest) (*KeyValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateValue not implemented")
}
func (*UnimplementedTritonServer) DeleteValue(ctx context.Context, req *DeleteValueRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteValue not implemented")
}

func RegisterTritonServer(s *grpc.Server, srv TritonServer) {
	s.RegisterService(&_Triton_serviceDesc, srv)
}

func _Triton_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/CreateStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).CreateStore(ctx, req.(*CreateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_GetStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).GetStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/GetStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).GetStore(ctx, req.(*GetStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_ListStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).ListStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/ListStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).ListStore(ctx, req.(*ListStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/DeleteStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).DeleteStore(ctx, req.(*DeleteStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_CreateValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).CreateValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/CreateValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).CreateValue(ctx, req.(*CreateValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_UpdateValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).UpdateValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/UpdateValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).UpdateValue(ctx, req.(*UpdateValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Triton_DeleteValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TritonServer).DeleteValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.Triton/DeleteValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TritonServer).DeleteValue(ctx, req.(*DeleteValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Triton_serviceDesc = grpc.ServiceDesc{
	ServiceName: "triton.Triton",
	HandlerType: (*TritonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStore",
			Handler:    _Triton_CreateStore_Handler,
		},
		{
			MethodName: "GetStore",
			Handler:    _Triton_GetStore_Handler,
		},
		{
			MethodName: "ListStore",
			Handler:    _Triton_ListStore_Handler,
		},
		{
			MethodName: "DeleteStore",
			Handler:    _Triton_DeleteStore_Handler,
		},
		{
			MethodName: "CreateValue",
			Handler:    _Triton_CreateValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _Triton_GetValue_Handler,
		},
		{
			MethodName: "UpdateValue",
			Handler:    _Triton_UpdateValue_Handler,
		},
		{
			MethodName: "DeleteValue",
			Handler:    _Triton_DeleteValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "triton.proto",
}
