// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/triton.proto

package triton

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{0}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KeyValue) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type StorageOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageOptions) Reset()         { *m = StorageOptions{} }
func (m *StorageOptions) String() string { return proto.CompactTextString(m) }
func (*StorageOptions) ProtoMessage()    {}
func (*StorageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{1}
}

func (m *StorageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageOptions.Unmarshal(m, b)
}
func (m *StorageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageOptions.Marshal(b, m, deterministic)
}
func (m *StorageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageOptions.Merge(m, src)
}
func (m *StorageOptions) XXX_Size() int {
	return xxx_messageInfo_StorageOptions.Size(m)
}
func (m *StorageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StorageOptions proto.InternalMessageInfo

type Storage struct {
	// ID of this storage, assigned by the server when the storage is created.
	Id                   int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Options              *StorageOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Storage) Reset()         { *m = Storage{} }
func (m *Storage) String() string { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()    {}
func (*Storage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{2}
}

func (m *Storage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storage.Unmarshal(m, b)
}
func (m *Storage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storage.Marshal(b, m, deterministic)
}
func (m *Storage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storage.Merge(m, src)
}
func (m *Storage) XXX_Size() int {
	return xxx_messageInfo_Storage.Size(m)
}
func (m *Storage) XXX_DiscardUnknown() {
	xxx_messageInfo_Storage.DiscardUnknown(m)
}

var xxx_messageInfo_Storage proto.InternalMessageInfo

func (m *Storage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Storage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Storage) GetOptions() *StorageOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type CreateStorageRequest struct {
	Options              *StorageOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateStorageRequest) Reset()         { *m = CreateStorageRequest{} }
func (m *CreateStorageRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStorageRequest) ProtoMessage()    {}
func (*CreateStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{3}
}

func (m *CreateStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStorageRequest.Unmarshal(m, b)
}
func (m *CreateStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStorageRequest.Marshal(b, m, deterministic)
}
func (m *CreateStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStorageRequest.Merge(m, src)
}
func (m *CreateStorageRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStorageRequest.Size(m)
}
func (m *CreateStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStorageRequest proto.InternalMessageInfo

func (m *CreateStorageRequest) GetOptions() *StorageOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type GetStorageRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStorageRequest) Reset()         { *m = GetStorageRequest{} }
func (m *GetStorageRequest) String() string { return proto.CompactTextString(m) }
func (*GetStorageRequest) ProtoMessage()    {}
func (*GetStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{4}
}

func (m *GetStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorageRequest.Unmarshal(m, b)
}
func (m *GetStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorageRequest.Marshal(b, m, deterministic)
}
func (m *GetStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorageRequest.Merge(m, src)
}
func (m *GetStorageRequest) XXX_Size() int {
	return xxx_messageInfo_GetStorageRequest.Size(m)
}
func (m *GetStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorageRequest proto.InternalMessageInfo

func (m *GetStorageRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListStorageRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStorageRequest) Reset()         { *m = ListStorageRequest{} }
func (m *ListStorageRequest) String() string { return proto.CompactTextString(m) }
func (*ListStorageRequest) ProtoMessage()    {}
func (*ListStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{5}
}

func (m *ListStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStorageRequest.Unmarshal(m, b)
}
func (m *ListStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStorageRequest.Marshal(b, m, deterministic)
}
func (m *ListStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStorageRequest.Merge(m, src)
}
func (m *ListStorageRequest) XXX_Size() int {
	return xxx_messageInfo_ListStorageRequest.Size(m)
}
func (m *ListStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStorageRequest proto.InternalMessageInfo

type DeleteStorageRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStorageRequest) Reset()         { *m = DeleteStorageRequest{} }
func (m *DeleteStorageRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStorageRequest) ProtoMessage()    {}
func (*DeleteStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{6}
}

func (m *DeleteStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorageRequest.Unmarshal(m, b)
}
func (m *DeleteStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorageRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorageRequest.Merge(m, src)
}
func (m *DeleteStorageRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStorageRequest.Size(m)
}
func (m *DeleteStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorageRequest proto.InternalMessageInfo

func (m *DeleteStorageRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetValueRequest struct {
	StorageId            int64    `protobuf:"varint,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Key                  []string `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueRequest) Reset()         { *m = GetValueRequest{} }
func (m *GetValueRequest) String() string { return proto.CompactTextString(m) }
func (*GetValueRequest) ProtoMessage()    {}
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{7}
}

func (m *GetValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueRequest.Unmarshal(m, b)
}
func (m *GetValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueRequest.Marshal(b, m, deterministic)
}
func (m *GetValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueRequest.Merge(m, src)
}
func (m *GetValueRequest) XXX_Size() int {
	return xxx_messageInfo_GetValueRequest.Size(m)
}
func (m *GetValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueRequest proto.InternalMessageInfo

func (m *GetValueRequest) GetStorageId() int64 {
	if m != nil {
		return m.StorageId
	}
	return 0
}

func (m *GetValueRequest) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetValueResponse struct {
	KeyValue             []*KeyValue `protobuf:"bytes,1,rep,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetValueResponse) Reset()         { *m = GetValueResponse{} }
func (m *GetValueResponse) String() string { return proto.CompactTextString(m) }
func (*GetValueResponse) ProtoMessage()    {}
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{8}
}

func (m *GetValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueResponse.Unmarshal(m, b)
}
func (m *GetValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueResponse.Marshal(b, m, deterministic)
}
func (m *GetValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueResponse.Merge(m, src)
}
func (m *GetValueResponse) XXX_Size() int {
	return xxx_messageInfo_GetValueResponse.Size(m)
}
func (m *GetValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueResponse proto.InternalMessageInfo

func (m *GetValueResponse) GetKeyValue() []*KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

type SetValueRequest struct {
	StorageId            int64       `protobuf:"varint,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	KeyValue             []*KeyValue `protobuf:"bytes,2,rep,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetValueRequest) Reset()         { *m = SetValueRequest{} }
func (m *SetValueRequest) String() string { return proto.CompactTextString(m) }
func (*SetValueRequest) ProtoMessage()    {}
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{9}
}

func (m *SetValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValueRequest.Unmarshal(m, b)
}
func (m *SetValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValueRequest.Marshal(b, m, deterministic)
}
func (m *SetValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValueRequest.Merge(m, src)
}
func (m *SetValueRequest) XXX_Size() int {
	return xxx_messageInfo_SetValueRequest.Size(m)
}
func (m *SetValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetValueRequest proto.InternalMessageInfo

func (m *SetValueRequest) GetStorageId() int64 {
	if m != nil {
		return m.StorageId
	}
	return 0
}

func (m *SetValueRequest) GetKeyValue() []*KeyValue {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

type SetValueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetValueResponse) Reset()         { *m = SetValueResponse{} }
func (m *SetValueResponse) String() string { return proto.CompactTextString(m) }
func (*SetValueResponse) ProtoMessage()    {}
func (*SetValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{10}
}

func (m *SetValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValueResponse.Unmarshal(m, b)
}
func (m *SetValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValueResponse.Marshal(b, m, deterministic)
}
func (m *SetValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValueResponse.Merge(m, src)
}
func (m *SetValueResponse) XXX_Size() int {
	return xxx_messageInfo_SetValueResponse.Size(m)
}
func (m *SetValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetValueResponse proto.InternalMessageInfo

type DeleteValueRequest struct {
	StorageId int64 `protobuf:"varint,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	// TODO: should or should not allow batch delete?
	Key                  []string `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteValueRequest) Reset()         { *m = DeleteValueRequest{} }
func (m *DeleteValueRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteValueRequest) ProtoMessage()    {}
func (*DeleteValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{11}
}

func (m *DeleteValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteValueRequest.Unmarshal(m, b)
}
func (m *DeleteValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteValueRequest.Marshal(b, m, deterministic)
}
func (m *DeleteValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteValueRequest.Merge(m, src)
}
func (m *DeleteValueRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteValueRequest.Size(m)
}
func (m *DeleteValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteValueRequest proto.InternalMessageInfo

func (m *DeleteValueRequest) GetStorageId() int64 {
	if m != nil {
		return m.StorageId
	}
	return 0
}

func (m *DeleteValueRequest) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

type DeleteValueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteValueResponse) Reset()         { *m = DeleteValueResponse{} }
func (m *DeleteValueResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteValueResponse) ProtoMessage()    {}
func (*DeleteValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fa6991ed2be2a7, []int{12}
}

func (m *DeleteValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteValueResponse.Unmarshal(m, b)
}
func (m *DeleteValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteValueResponse.Marshal(b, m, deterministic)
}
func (m *DeleteValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteValueResponse.Merge(m, src)
}
func (m *DeleteValueResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteValueResponse.Size(m)
}
func (m *DeleteValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteValueResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*KeyValue)(nil), "triton.KeyValue")
	proto.RegisterType((*StorageOptions)(nil), "triton.StorageOptions")
	proto.RegisterType((*Storage)(nil), "triton.Storage")
	proto.RegisterType((*CreateStorageRequest)(nil), "triton.CreateStorageRequest")
	proto.RegisterType((*GetStorageRequest)(nil), "triton.GetStorageRequest")
	proto.RegisterType((*ListStorageRequest)(nil), "triton.ListStorageRequest")
	proto.RegisterType((*DeleteStorageRequest)(nil), "triton.DeleteStorageRequest")
	proto.RegisterType((*GetValueRequest)(nil), "triton.GetValueRequest")
	proto.RegisterType((*GetValueResponse)(nil), "triton.GetValueResponse")
	proto.RegisterType((*SetValueRequest)(nil), "triton.SetValueRequest")
	proto.RegisterType((*SetValueResponse)(nil), "triton.SetValueResponse")
	proto.RegisterType((*DeleteValueRequest)(nil), "triton.DeleteValueRequest")
	proto.RegisterType((*DeleteValueResponse)(nil), "triton.DeleteValueResponse")
}

func init() {
	proto.RegisterFile("api/triton.proto", fileDescriptor_c9fa6991ed2be2a7)
}

var fileDescriptor_c9fa6991ed2be2a7 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x5d, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb1, 0x4d, 0xdb, 0x64, 0x02, 0x8d, 0x19, 0x02, 0x04, 0x53, 0x90, 0xb5, 0x20, 0x14,
	0x21, 0xd1, 0x40, 0x78, 0xeb, 0x0b, 0xe2, 0xb3, 0x45, 0x20, 0x21, 0xad, 0x25, 0x5e, 0x23, 0xd3,
	0x8c, 0xa2, 0x55, 0x82, 0xd7, 0xd8, 0xdb, 0x48, 0xe1, 0x91, 0x2b, 0x70, 0x23, 0xae, 0xc0, 0x15,
	0x38, 0x08, 0xf2, 0x7e, 0x94, 0xda, 0x0e, 0x02, 0xd4, 0xb7, 0xd9, 0xdd, 0xff, 0xfe, 0x76, 0x66,
	0xfe, 0x63, 0x43, 0x98, 0xe6, 0x62, 0xac, 0x0a, 0xa1, 0x64, 0xb6, 0x9f, 0x17, 0x52, 0x49, 0xdc,
	0x36, 0xab, 0x68, 0x6f, 0x2e, 0xe5, 0x7c, 0x49, 0xe3, 0x4a, 0x90, 0x66, 0x99, 0x54, 0xa9, 0x12,
	0x32, 0x2b, 0x8d, 0x8a, 0xbd, 0x86, 0xce, 0x5b, 0x5a, 0x7f, 0x48, 0x97, 0x27, 0x84, 0x21, 0x04,
	0x0b, 0x5a, 0x0f, 0xbd, 0xd8, 0x1b, 0x75, 0x79, 0x15, 0xe2, 0x00, 0xb6, 0x56, 0xd5, 0xd1, 0xd0,
	0x8f, 0xbd, 0xd1, 0x25, 0x6e, 0x16, 0x88, 0x70, 0xb1, 0x14, 0x5f, 0x68, 0x18, 0xc4, 0xde, 0x68,
	0x8b, 0xeb, 0x98, 0x85, 0xb0, 0x9b, 0x28, 0x59, 0xa4, 0x73, 0x7a, 0x9f, 0x6b, 0x3e, 0x9b, 0xc2,
	0x8e, 0xdd, 0xc1, 0x5d, 0xf0, 0xc5, 0x4c, 0x73, 0x03, 0xee, 0x8b, 0x59, 0x05, 0xc8, 0xd2, 0x4f,
	0x86, 0xda, 0xe5, 0x3a, 0xc6, 0x47, 0xb0, 0x23, 0xcd, 0x4d, 0xcd, 0xed, 0x4d, 0xae, 0xef, 0xdb,
	0x72, 0xea, 0x5c, 0xee, 0x64, 0xec, 0x08, 0x06, 0x2f, 0x0a, 0x4a, 0x15, 0x59, 0x01, 0xa7, 0xcf,
	0x27, 0x54, 0xaa, 0xb3, 0x24, 0xef, 0xdf, 0x48, 0x77, 0xe1, 0xca, 0x21, 0xa9, 0x06, 0xa6, 0x91,
	0x34, 0x1b, 0x00, 0xbe, 0x13, 0x65, 0x43, 0xc5, 0xee, 0xc3, 0xe0, 0x25, 0x2d, 0xa9, 0x95, 0x44,
	0xf3, 0xf6, 0x73, 0xe8, 0x1f, 0x92, 0xd2, 0x7d, 0x76, 0x92, 0xdb, 0x00, 0xa5, 0xb9, 0x34, 0x3d,
	0x95, 0x76, 0xed, 0xce, 0x9b, 0x99, 0x73, 0xc3, 0x8f, 0x03, 0xeb, 0x06, 0x7b, 0x06, 0xe1, 0x6f,
	0x46, 0x99, 0xcb, 0xac, 0x24, 0x7c, 0x08, 0xdd, 0x05, 0xad, 0xa7, 0xc6, 0x25, 0x2f, 0x0e, 0x46,
	0xbd, 0x49, 0xe8, 0xca, 0x75, 0xc6, 0xf2, 0xce, 0xc2, 0x46, 0x6c, 0x0a, 0xfd, 0xe4, 0xff, 0xd2,
	0xa8, 0x3d, 0xe0, 0xff, 0xf5, 0x01, 0x84, 0x30, 0x69, 0xe4, 0xc8, 0x5e, 0x01, 0x9a, 0x1e, 0x9d,
	0xaf, 0xfc, 0x6b, 0x70, 0xb5, 0x86, 0x31, 0xf4, 0xc9, 0x77, 0xff, 0x74, 0xf4, 0x12, 0x2a, 0x56,
	0xe2, 0x98, 0x70, 0x06, 0x97, 0x6b, 0x93, 0x81, 0x7b, 0x2e, 0xe3, 0x4d, 0x03, 0x13, 0xf5, 0x1b,
	0xf3, 0xc1, 0xee, 0x7d, 0xfd, 0xf1, 0xf3, 0x9b, 0x7f, 0x87, 0xdd, 0x1c, 0xaf, 0x1e, 0xdb, 0x8f,
	0x6a, 0x6c, 0x33, 0x3b, 0x38, 0xd6, 0x84, 0x03, 0xef, 0x01, 0x3e, 0x85, 0x8e, 0xb3, 0x03, 0x6f,
	0x38, 0x44, 0xc3, 0xe4, 0x68, 0xd8, 0x3e, 0xb0, 0x5d, 0xb9, 0x50, 0x01, 0x92, 0x16, 0x20, 0xf9,
	0x13, 0x20, 0x69, 0x03, 0x8e, 0xa0, 0x77, 0xa6, 0x23, 0x18, 0x39, 0x69, 0xbb, 0xdb, 0xd1, 0xad,
	0x8d, 0x67, 0x8e, 0xf4, 0x71, 0x5b, 0xff, 0x0d, 0x9e, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xda,
	0x92, 0x2a, 0xa2, 0x47, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageServiceClient interface {
	CreateStorage(ctx context.Context, in *CreateStorageRequest, opts ...grpc.CallOption) (*Storage, error)
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error)
	DeleteValue(ctx context.Context, in *DeleteValueRequest, opts ...grpc.CallOption) (*DeleteValueResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) CreateStorage(ctx context.Context, in *CreateStorageRequest, opts ...grpc.CallOption) (*Storage, error) {
	out := new(Storage)
	err := c.cc.Invoke(ctx, "/triton.StorageService/CreateStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, "/triton.StorageService/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error) {
	out := new(SetValueResponse)
	err := c.cc.Invoke(ctx, "/triton.StorageService/SetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteValue(ctx context.Context, in *DeleteValueRequest, opts ...grpc.CallOption) (*DeleteValueResponse, error) {
	out := new(DeleteValueResponse)
	err := c.cc.Invoke(ctx, "/triton.StorageService/DeleteValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
type StorageServiceServer interface {
	CreateStorage(context.Context, *CreateStorageRequest) (*Storage, error)
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error)
	DeleteValue(context.Context, *DeleteValueRequest) (*DeleteValueResponse, error)
}

// UnimplementedStorageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStorageServiceServer struct {
}

func (*UnimplementedStorageServiceServer) CreateStorage(ctx context.Context, req *CreateStorageRequest) (*Storage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStorage not implemented")
}
func (*UnimplementedStorageServiceServer) GetValue(ctx context.Context, req *GetValueRequest) (*GetValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (*UnimplementedStorageServiceServer) SetValue(ctx context.Context, req *SetValueRequest) (*SetValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValue not implemented")
}
func (*UnimplementedStorageServiceServer) DeleteValue(ctx context.Context, req *DeleteValueRequest) (*DeleteValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteValue not implemented")
}

func RegisterStorageServiceServer(s *grpc.Server, srv StorageServiceServer) {
	s.RegisterService(&_StorageService_serviceDesc, srv)
}

func _StorageService_CreateStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.StorageService/CreateStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateStorage(ctx, req.(*CreateStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.StorageService/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.StorageService/SetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SetValue(ctx, req.(*SetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/triton.StorageService/DeleteValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteValue(ctx, req.(*DeleteValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "triton.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStorage",
			Handler:    _StorageService_CreateStorage_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _StorageService_GetValue_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _StorageService_SetValue_Handler,
		},
		{
			MethodName: "DeleteValue",
			Handler:    _StorageService_DeleteValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/triton.proto",
}
